"""add_source_and_missing_columns

Revision ID: 761125501df0
Revises: None
Create Date: 2026-08-11 05:09:55.530299+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761125501df0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('anomaly_alerts', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('anomaly_alerts', sa.Column('acknowledged_by', sa.String(length=100), nullable=True))
    op.add_column('anomaly_alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('anomaly_alerts', sa.Column('resolved_by', sa.String(length=100), nullable=True))
    op.add_column('anomaly_alerts', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('telemetry_events', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('telemetry_events', sa.Column('external_event_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_telemetry_events_external_event_id'), 'telemetry_events', ['external_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_events_external_event_id'), table_name='telemetry_events')
    op.drop_column('telemetry_events', 'external_event_id')
    op.drop_column('telemetry_events', 'source')
    op.drop_column('sessions', 'source')
    op.drop_column('anomaly_alerts', 'status')
    op.drop_column('anomaly_alerts', 'resolved_by')
    op.drop_column('anomaly_alerts', 'resolved_at')
    op.drop_column('anomaly_alerts', 'acknowledged_by')
    op.drop_column('anomaly_alerts', 'acknowledged_at')
    op.drop_column('agents', 'source')
    # ### end Alembic commands ###
