"""add_source_and_missing_columns

Revision ID: 761125501df0
Revises: None
Create Date: 2026-08-11 05:09:55.530299+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761125501df0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    columns = {
        "agents": {"source": sa.String(length=20)},
        "anomaly_alerts": {
            "acknowledged_at": sa.DateTime(),
            "acknowledged_by": sa.String(length=100),
            "resolved_at": sa.DateTime(),
            "resolved_by": sa.String(length=100),
            "status": sa.String(length=20),
        },
        "sessions": {"source": sa.String(length=20)},
        "telemetry_events": {
            "source": sa.String(length=20),
            "external_event_id": sa.String(length=100),
            "parent_agent_id": sa.String(length=50),
            "parent_event_id": sa.BigInteger(),
            "interaction_type": sa.String(length=30),
            "impact_status": sa.String(length=30),
        },
    }
    for table_name, table_columns in columns.items():
        existing_columns = {column["name"] for column in inspector.get_columns(table_name)}
        for column_name, column_type in table_columns.items():
            if column_name not in existing_columns:
                op.add_column(table_name, sa.Column(column_name, column_type, nullable=True))

    existing_indexes = {
        index["name"] for index in inspector.get_indexes("telemetry_events")
    }
    index_name = op.f("ix_telemetry_events_external_event_id")
    if index_name not in existing_indexes:
        op.create_index(index_name, "telemetry_events", ["external_event_id"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_events_external_event_id'), table_name='telemetry_events')
    op.drop_column('telemetry_events', 'external_event_id')
    op.drop_column('telemetry_events', 'source')
    op.drop_column('sessions', 'source')
    op.drop_column('anomaly_alerts', 'status')
    op.drop_column('anomaly_alerts', 'resolved_by')
    op.drop_column('anomaly_alerts', 'resolved_at')
    op.drop_column('anomaly_alerts', 'acknowledged_by')
    op.drop_column('anomaly_alerts', 'acknowledged_at')
    op.drop_column('agents', 'source')
    # ### end Alembic commands ###
